### ISSUE TITLE
minitest-chef-handler with turn fails

### ISSUE THREAD

**Issue by melezhik** [chef-boneyard/minitest-chef-handler#57]
I try to colourize output of chef minitest with turn, but fail:

$ cat solo.rb

```
log_level          :info
log_location       STDOUT
file_cache_path    "#{Dir.pwd}/cache"
file_backup_path   "#{Dir.pwd}/backup"
cache_options({ :path => "#{Dir.pwd}/checksums", :skip_expires => true})
Mixlib::Log::Formatter.show_time = true
cookbook_path [  
    Dir.pwd,
    "#{Dir.pwd}/cookbooks"
]


require 'minitest-chef-handler'
require 'turn/autorun'
#Turn.config.format = :pretty

report_handlers << MiniTest::Chef::Handler.new(:verbose => true)

---
```

$ rvmsudo bundle exec  chef-solo  -c solo.rb

```
[2013-04-24T14:47:14+04:00] INFO: Report handlers complete
Chef Client finished, 4 resources updated
/home/melezhik/.rvm/gems/ruby-1.9.3-p392/gems/minitest-4.7.3/lib/minitest/unit.rb:1025:in `block in process_args': invalid option: -c (OptionParser::InvalidOption)
from /home/melezhik/.rvm/gems/ruby-1.9.3-p392/gems/minitest-4.7.3/lib/minitest/unit.rb:1004:in `new'
from /home/melezhik/.rvm/gems/ruby-1.9.3-p392/gems/minitest-4.7.3/lib/minitest/unit.rb:1004:in `process_args'
from /home/melezhik/.rvm/gems/ruby-1.9.3-p392/gems/minitest-4.7.3/lib/minitest/unit.rb:1054:in `_run'
from /home/melezhik/.rvm/gems/ruby-1.9.3-p392/gems/minitest-4.7.3/lib/minitest/unit.rb:1047:in `run'
from /home/melezhik/.rvm/gems/ruby-1.9.3-p392/gems/minitest-4.7.3/lib/minitest/unit.rb:784:in `block in autorun'
```

**Comment by cgunasree08** [comment]
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).
